package br.univali.portugol.plugin.gogoboard.ui.telas;

import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;

/**
 * Classe da janela utilizada para exibir o código Logo Cricket.
 *
 * @author Ailton Cardoso Jr
 * @version 1.0
 */
public class JanelaLogoCricket extends javax.swing.JPanel implements Themeable {

    /**
     * Construtor padrão da janela do monitor do código Logo Cricket.
     */
    public JanelaLogoCricket() {
        initComponents();
        textAreaCodigoLogo.setEditable(false);
        configurarCores();
    }

    /**
     * Método para adicionar o código Logo no textArea.
     */
    public void setCodigoLogo(String codigoFonte) {
        textAreaCodigoLogo.setText(codigoFonte);

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                painelRolagem.getVerticalScrollBar().setValue(0);
                painelRolagem.getHorizontalScrollBar().setValue(0);
            }
        });
    }

    /**
     * Sobrescrita do método para configurar as cores dos elementos da tela.
     *
     * @see Themeable
     */
    @Override
    public void configurarCores() {
        if (WeblafUtils.weblafEstaInstalado()) {
            WeblafUtils.configuraWebLaf(textAreaCodigoLogo);
            WeblafUtils.configuraWebLaf(painelRolagem);
        }
        painelPrincipal.setBackground(ColorController.COR_PRINCIPAL);
        textAreaCodigoLogo.setBackground(ColorController.COR_PRINCIPAL);
        textAreaCodigoLogo.setForeground(ColorController.COR_LETRA);
        textAreaCodigoLogo.setSelectionColor(ColorController.COR_DESTAQUE);
        textAreaCodigoLogo.setSelectedTextColor(ColorController.FUNDO_ESCURO);
        painelRolagem.setBorder(BorderFactory.createLineBorder(ColorController.FUNDO_ESCURO));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelRolagem = new javax.swing.JScrollPane();
        textAreaCodigoLogo = new javax.swing.JTextArea();

        textAreaCodigoLogo.setEditable(false);
        textAreaCodigoLogo.setColumns(20);
        textAreaCodigoLogo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        textAreaCodigoLogo.setRows(5);
        painelRolagem.setViewportView(textAreaCodigoLogo);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JScrollPane painelRolagem;
    private org.fife.ui.rtextarea.RTextArea rTextArea1;
    private javax.swing.JTextArea textAreaCodigoLogo;
    // End of variables declaration//GEN-END:variables
}
